---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Australia/Sydney"
  KUBE_VIP_ADDR: 192.168.16.254
  K8S_CLUSTER_CIDR: 10.42.0.0/16
  K8S_POD_CIDR: 10.42.0.0/16
  K8S_SERVICE_CIDR: 10.43.0.0/16
  K8S_LB_CIDR: 10.44.0.0/16
  SERVER_CIDR: 192.168.16.0/24
  ROUTER_IP: 192.168.16.1
  NODE_CIDR: 192.168.16.0/24
  INGRESS_NGINX_EXTERNAL_IP: 10.44.0.1
  INGRESS_NGINX_INTERNAL_IP: 10.44.0.2
  K8S_GATEWAY_IP: 10.44.0.3
  POSTGRES_IP: 10.44.0.17
  MQTT_IP: 10.44.0.16
  HASS_IP: 10.44.0.18
  LOCAL_DOMAIN: home.lan
  VOLSYNC_RESTIC_REPOSITORY: s3:http://minio.home.lan:9000/volsync
  # K8S_GW_LB_IP: "192.168.16.253"
  # NGINX_EXT_LB_IP: "192.168.16.252"
  # NGINX_INT_LB_IP: "192.168.16.251"
  # POSGRES_LB_IP: "192.168.16.250"
  # MQTT_LB_IP: "192.168.16.249"
  NFS_IP: 192.168.16.30
  SYNOLOGY_IP: 192.168.16.30
